### ISSUE TITLE
take advantage of libfringe for context switch

### ISSUE THREAD

**Issue by Xudong-Huang** [Xudong-Huang/generator-rs#4]
take advantage of [libfringe](https://github.com/edef1c/libfringe) context switch

please ref https://github.com/Xudong-Huang/may/issues/31

**Comment by alkis** [comment]
there are other ideas worth taking from libfringe:
- generator constructor does not allocate
- resume/suspend take arguments which is nicer then set_co_para/get_co_para

**Comment by Xudong-Huang** [comment]
now the libfringe can't handle panic properly (https://github.com/edef1c/libfringe/issues/75), don't know why. and it seems that the crate has no update for a long time.

I will do more investigate to see if we can safely use the new context switch method based on libfringe. there is no clue how to handle the return instructions in libfringe. if user want return a useful result, it seems it not supported.

Some thing like this should work...
```rust
fn test_return() {
    let mut g = Gn::new_scoped(|_s| {
        return 42;
    });
    assert_eq!(g.next(), Some(42));
    assert!(g.is_done());
}
```

**Comment by Xudong-Huang** [comment]
I bench for both swap on my computer, ~~seems that the context switching doesn't speed as 10 fold, but libfringe is really faster.~~ the libfringe's bench is based on 10 times context switching for each bench iter. So it more than 10 times faster than generator-rs,  this is really amazing. 

generator-rs
```sh
test scoped_yield_bench      ... bench:          36 ns/iter (+/- 0)
test single_yield_bench      ... bench:          39 ns/iter (+/- 0)
test single_yield_with_bench ... bench:          36 ns/iter (+/- 0)
```

libfringe (Amanieu/unwind branch)
```sh
test arch::tests::swap ... bench:          25 ns/iter (+/- 0)
```

**Comment by Xudong-Huang** [comment]
```diff
$ cargo benchcmp unix_master.txt unix_libfringe.txt 
  name                     unix_master.txt ns/iter  unix_libfringe.txt ns/iter  diff ns/iter   diff %  speedup 
- create_gen               103                      199                                   96   93.20%   x 0.52 
- fnbox_bench              40                       48                                     8   20.00%   x 0.83 
- init_gen                 25                       125                                  100  400.00%   x 0.20 
+ scoped_yield_bench       30                       15                                   -15  -50.00%   x 2.00 
+ single_yield_bench       33                       16                                   -17  -51.52%   x 2.06 
+ single_yield_with_bench  30                       14                                   -16  -53.33%   x 2.14 
```

The init would take an extra yield context switch which is not necessary, but need a way to save the passed in closure.

Also the `libfringe` branch only support nightly build because we use the special asm clobber

The performance of context switch improved about  2 times. but usually this is not the bottleneck for a system, e.g. the coroutine context switch.

**Comment by Xudong-Huang** [comment]
remove the unnecessary init context switch

```diff
$ cargo benchcmp unix_master.txt unix_libfringe_1.txt
 name                     unix_master.txt ns/iter  unix_libfringe_1.txt ns/iter  diff ns/iter   diff %  speedup 
+ create_gen               103                      94                                      -9   -8.74%   x 1.10 
- fnbox_bench              40                       42                                       2    5.00%   x 0.95 
+ init_gen                 25                       23                                      -2   -8.00%   x 1.09 
+ scoped_yield_bench       30                       17                                     -13  -43.33%   x 1.76 
+ single_yield_bench       33                       18                                     -15  -45.45%   x 1.83 
+ single_yield_with_bench  30                       15                                     -15  -50.00%   x 2.00
```

**Comment by Xudong-Huang** [comment]
the tech used in this branch is hard to port to stable because we depend on inline assembly feature which is not likely to be stable very soon

**Comment by 2dav** [comment]
Hey,
playing with coroutines and `libfringe`, it turned out that a vital part of context switching performance lies in `pop+jmp` vs `ret`.
[This thread on HN](https://news.ycombinator.com/item?id=17225798) sheds some light
>  `jmp rax` (or any register really) uses the indirect jump prediction, while `ret` uses a special dedicated predictor that uses a stack (the Return Stack Buffer or RSB), populated by `call` instructions, to predict the return address. In the coroutine case, the `ret` does not jump to the address of the last `call` so it will be mispredicted many time. 

Changing two lines on ~master:
https://github.com/Xudong-Huang/generator-rs/blob/5888dac74f498a3c176f7b23c2260822a3928f48/src/detail/asm/asm_x86_64_sysv_elf_gas.S#L43
```asm
pop %rax
jmp *%rax
```
`x86_64 zen3`
| name | before ns/iter | after ns/iter | diff ns/iter | diff % | speedup |
|---|---|---|---|---|---|
| fnbox_bench | 20 | 15 | -5 | -25.00% | x 1.33 |
| init_gen | 8 | 8 | 0 | 0.00% | x 1.00 |
| scoped_yield_bench | 22 | 9 | -13 | -59.09% | x 2.44 |
| single_yield_bench | 25 | 10 | -15 | -60.00% | x 2.50 |
| single_yield_with_bench | 22 | 9 | -13 | -59.09% | x 2.44 |

`perf` output for one of the benches
  |  | before | after |  |
|---|---|---|---|
| page-faults | 779.883 | 6457 | /sec |
| stalled-cycles-frontend | 12.93% | 0.08%  | frontend cycles idle |
| stalled-cycles-backend | 1.30% | 48.56%  | backend cycles idle |
| instructions | 1.32 | 3.01 | insn per cycle |
| branches | 1.247 | 2.754  | G/sec |
| branch-misses | 6.61% | 0.03%  | of all branches |
